### ISSUE TITLE
Множественные нули

### ISSUE THREAD

**Issue by AntuanDar** [AntuanDar/SimpleCalculator#11]
Если ввести несколько нулей подряд, то будет результат 0000
Надо делать проверку, что после нуля идет "." и тогда любые цифры, чтобы не получилось 01 001 и т.д.

**Comment by se4oev** [comment]
Исправлено. После первого нуля нельзя вводить второй, если второй символ цифра, то первый ноль удаляется. Если первый символ точка, то добавляется ноль.
