### ISSUE TITLE
Текстфилд

### ISSUE THREAD

**Issue by AntuanDar** [AntuanDar/SimpleCalculator#3]
запретить ввод текста в текстфилд
повесить слушатель на кнопки 0 - 9 (включая numpud)
введенные цифры должны отображаться в текстфилде
выравнивание по правому краю

**Comment by se4oev** [comment]
Ввод текста в textField запрещен (setEditable(false)).
Слушатели на кнопки экранные добавлены. Слушатели на кнопки клавиатуры добавлены, если нажатая кнопка не является цифрой (проверяется через try {} catch), то ввод не осущетсвляется
