### ISSUE TITLE
Кнопки

### ISSUE THREAD

**Issue by AntuanDar** [AntuanDar/SimpleCalculator#4]
Повесит слушатель мыши на кнопки
при нажатии на кнопку в текстфилде дожна отобразиться цифра
кнопки + - = \ % отображаться не должны (если в текстфилде нет числа)
елси вначале есть число, то вид следующий (3 +)

**Comment by se4oev** [comment]
Добавлены слушатели мышки на кнопки, при нажатии на кнопки 0-9 отображаются цифры, при нажатии на кнопки + - = \ % отображается знак, если ранее было введено число.
