### ISSUE TITLE
Вычисление

### ISSUE THREAD

**Issue by AntuanDar** [AntuanDar/SimpleCalculator#5]
При нажатие на кнопку "=" должен запуститься метод вычисления (пока только сложение для двух операндов)
(например ввели число, нажали плюс, первое число считали в переменную для первого операнда, потом добавили плюс в текстфилд, стали "запоминать" второе число, в какую-нибудь строку, до нажатия равно
В общем не суть, в дальнейшем в любом случае будем парсить строку и разделять операции по операторам в зависимости от приоритета
и в текстфилде должен отобразиться результат вычисления
запретить ввод 0 после действия делить
при вводе (3 + =) должно отобразиться 3 (для всех аналогичных действий так же)

**Comment by se4oev** [comment]
Сложение для двух операндов реализовано. Первый операнд считывается в переменную firstOperand после нажатия плюса, потом после ввода второго операнда и нажатия = считывается второй операнд и производится вычисление с выводом на экран.
А вот запрет ввода 0 после действия делить логически неправилен, потому что можно ввести 0,25 например. Можно реализовать запрет деления на ноль либо выводом сообщения "Деление на ноль невозможно" (это я подсмотрел в виндовом калькуляторе), либо просто ничего не делать если второй операнд равен нулю и вызвано деление
